:imagesdir: ../../assets/images
include::../style.adoc[]

== Module 6: {streams}のセキュリティ
{m6}


組織がミッションクリティカルなデータパイプラインにKafkaを使用することが増えるにつれ、クラスタのセキュリティ確保が不可欠になっています。このモジュールでは、Kafkaセキュリティの主要な側面を紹介し、信頼性が高くコンプライアンスに準拠したイベントストリーミングプラットフォームを構築するための基礎を築きます。

Kafkaのセキュリティは、4つの主要な柱に焦点を当てています。

* *Authentication – 接続しているユーザーの検証*
Kafkaは、TLS証明書(SSL)、SASL/PLAIN、SCRAM、OAuthなどの複数の認証メカニズムをサポートしています。これらにより、認可されたクライアント、Broker、ユーザーのみが接続を確立できるようになります。

* *Authorization (ACLs) – 各ユーザー/アプリケーションが実行できる操作の制御*
Authorizationは、特定のユーザーまたはクライアントがKafkaクラスタで実行できるアクションを決定します。KafkaはAccess Control Lists (ACLs)を使用して、詳細な方法で権限を付与または拒否します。例えば、ユーザーはTopicから読み取ることはできても、書き込みはできないようにすることができます。

* *Encryption – 転送中のデータの保護*
{streams}はTransport Layer Security (TLS)をサポートしています。これは暗号化通信のためのプロトコルです。Streams for Apache Kafkaコンポーネント間の通信は常に暗号化されます。Kafkaとクライアント間でTLS暗号化通信を設定するには、KafkaカスタムリソースでListenerを設定できます。


=== アクティビティ概要
このモジュールでは、Authentication、Authorization、Encryptionなど、最も一般的なKafkaセキュリティ機能について学習します。また、これらの機能をKafkaクラスタに適用する方法についても学びます。





